name: Deploy

on:
  workflow_dispatch:
    inputs:
      network:
        description: "Network to deploy to"
        required: true
        type: choice
        options:
          - bsc-testnet
          - bsc
      verify:
        description: "Verify on BscScan"
        required: false
        type: boolean
        default: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.network }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Compile contracts
        run: npm run compile

      - name: Run tests
        run: npm test

      - name: Deploy to ${{ github.event.inputs.network }}
        env:
          PRIVATE_KEY: ${{ secrets.DEPLOYER_PRIVATE_KEY }}
          BSCSCAN_API_KEY: ${{ secrets.BSCSCAN_API_KEY }}
          USD1_MAINNET: ${{ secrets.USD1_MAINNET }}
          USD1_TESTNET: ${{ secrets.USD1_TESTNET }}
        run: |
          npm run deploy:${{ github.event.inputs.network == 'bsc' && 'mainnet' || 'testnet' }}

      - name: Verify on BscScan
        if: ${{ github.event.inputs.verify == 'true' }}
        env:
          BSCSCAN_API_KEY: ${{ secrets.BSCSCAN_API_KEY }}
        run: |
          sleep 30
          npm run verify:${{ github.event.inputs.network == 'bsc' && 'mainnet' || 'testnet' }}

      - name: Upload deployment artifacts
        uses: actions/upload-artifact@v3
        with:
          name: deployment-${{ github.event.inputs.network }}
          path: |
            deployments/
            artifacts/

      - name: Create deployment report
        run: |
          echo "# Deployment Report" > deployment-report.md
          echo "" >> deployment-report.md
          echo "**Network:** ${{ github.event.inputs.network }}" >> deployment-report.md
          echo "**Date:** $(date)" >> deployment-report.md
          echo "**Commit:** ${{ github.sha }}" >> deployment-report.md
          echo "" >> deployment-report.md
          echo "## Contracts" >> deployment-report.md
          echo "" >> deployment-report.md
          cat deployments/*/deployment-info.json >> deployment-report.md

      - name: Comment on PR
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const report = fs.readFileSync('deployment-report.md', 'utf8');
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: report
            });
